#  Import Libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# Load the Data

In [9]:
df=pd.read_csv("/content/drive/MyDrive/Datasets/CarPrice_Assignment.csv")

In [10]:
df.head()


car_ID  symboling                   CarName  ... citympg highwaympg    price
0       1          3        alfa-romero giulia  ...      21         27  13495.0
1       2          3       alfa-romero stelvio  ...      21         27  16500.0
2       3          1  alfa-romero Quadrifoglio  ...      19         26  16500.0
3       4          2               audi 100 ls  ...      24         30  13950.0
4       5          2                audi 100ls  ...      18         22  17450.0

[5 rows x 26 columns]

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   car_ID            205 non-null    int64  
 1   symboling         205 non-null    int64  
 2   CarName           205 non-null    object 
 3   fueltype          205 non-null    object 
 4   aspiration        205 non-null    object 
 5   doornumber        205 non-null    object 
 6   carbody           205 non-null    object 
 7   drivewheel        205 non-null    object 
 8   enginelocation    205 non-null    object 
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64  
 14  enginetype        205 non-null    object 
 15  cylindernumber    205 non-null    object 
 16  enginesize        205 non-null    int64  
 1

# Drop Unnecessary Columns

In [12]:
df.drop(['car_ID', 'symboling', 'CarName'], axis=1, inplace=True)
x = df.iloc[:, :-1].values #independent variables
y = df.iloc[:, -1].values #dependent variable, price

In [15]:
x

array([[0.0, 1.0, 1.0, ..., 5000, 21, 27],
       [0.0, 1.0, 1.0, ..., 5000, 21, 27],
       [0.0, 1.0, 1.0, ..., 5000, 19, 26],
       ...,
       [0.0, 1.0, 1.0, ..., 5500, 18, 23],
       [1.0, 0.0, 0.0, ..., 4800, 26, 27],
       [0.0, 1.0, 0.0, ..., 5400, 19, 25]], dtype=object)

In [16]:
y

array([13495.   , 16500.   , 16500.   , 13950.   , 17450.   , 15250.   ,
       17710.   , 18920.   , 23875.   , 17859.167, 16430.   , 16925.   ,
       20970.   , 21105.   , 24565.   , 30760.   , 41315.   , 36880.   ,
        5151.   ,  6295.   ,  6575.   ,  5572.   ,  6377.   ,  7957.   ,
        6229.   ,  6692.   ,  7609.   ,  8558.   ,  8921.   , 12964.   ,
        6479.   ,  6855.   ,  5399.   ,  6529.   ,  7129.   ,  7295.   ,
        7295.   ,  7895.   ,  9095.   ,  8845.   , 10295.   , 12945.   ,
       10345.   ,  6785.   ,  8916.5  ,  8916.5  , 11048.   , 32250.   ,
       35550.   , 36000.   ,  5195.   ,  6095.   ,  6795.   ,  6695.   ,
        7395.   , 10945.   , 11845.   , 13645.   , 15645.   ,  8845.   ,
        8495.   , 10595.   , 10245.   , 10795.   , 11245.   , 18280.   ,
       18344.   , 25552.   , 28248.   , 28176.   , 31600.   , 34184.   ,
       35056.   , 40960.   , 45400.   , 16503.   ,  5389.   ,  6189.   ,
        6669.   ,  7689.   ,  9959.   ,  8499.   , 

# Encoding Categorical Data

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer( transformers= [('encoder', OneHotEncoder(), [0, 1 ,2 ,3 ,4, 5, 11, 12, 14])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [14]:
x

array([[0.0, 1.0, 1.0, ..., 5000, 21, 27],
       [0.0, 1.0, 1.0, ..., 5000, 21, 27],
       [0.0, 1.0, 1.0, ..., 5000, 19, 26],
       ...,
       [0.0, 1.0, 1.0, ..., 5500, 18, 23],
       [1.0, 0.0, 0.0, ..., 4800, 26, 27],
       [0.0, 1.0, 0.0, ..., 5400, 19, 25]], dtype=object)

# Split the Dataset into Training Set and Test Set

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 15)

# Training the Multiple Linear Regression Model on the Training Set

In [18]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

# Predicting the Test Set Results

In [20]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision = 2) 

In [21]:
y_pred

array([27719.24, 21324.63, 20819.66,  8185.15,  7001.41, 17339.24,
        5676.54,  5623.66,  6082.53,  7952.45, 32959.69, 32930.61,
        6126.87,   538.07,  4519.66,  9107.52, 20618.76, 12427.73,
        7565.51, 12215.68, 13390.24,  8920.78,  7468.74, 16106.84,
       16959.91,  9405.94,  8278.9 ,  7277.12,  5858.17, 17106.78,
        5780.23,  6116.72, 12187.58,  3999.04, 38113.76, 26007.38,
       11692.13, 10827.76, 17470.91, 13098.9 ,  9179.65])

# Calculate the Accuracy

In [22]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.8454186173408362